### PR TITLE
feat: add support for version 293.0.2.0.84

### PR DESCRIPTION
**Pull request by rmnscnce**

### CODE REVIEW

**Comment by xHookman** [comment]
Sorry i will not add for absolutely each version of instagram a supported version, otherwise it will be horrible in app haha

**Comment by rmnscnce** [comment]
I think it would be for the best if you'd allow custom class names to be hooked because I'm in the alpha channel and it gets updates literally twice a day.

**Comment by ReSo7200** [comment]
He already done that, please use the second version...

**Comment by rmnscnce** [comment]
Ah, I see that the update didn't get through the LSPosed repo. Thanks for the tip @ReSo7200!

**Pull request closed without merging**
